services:
  fintrack:
    build: .
    container_name: fintrack
    restart: unless-stopped
    env_file:
      - .env.local
    expose:
      - "3000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fintrack.rule=Host(`fintrack.ethlab.fr`)"
      - "traefik.http.routers.fintrack.entrypoints=websecure"
      - "traefik.http.routers.fintrack.tls.certresolver=mytlschallenge"
      - "traefik.http.services.fintrack.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
